# Generated by Django 2.2 on 2021-03-20 10:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('nft_id', models.CharField(max_length=64)),
                ('nft_address', models.CharField(max_length=64)),
                ('ipns', models.CharField(max_length=64)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='core.Artist')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
                ('sig', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=3)),
                ('ipns', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('msg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='core.Item')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
