# Generated by Django 2.2 on 2021-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='wallet_address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='ipns',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sign',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sign',
            name='ipns',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sig',
            field=models.CharField(max_length=512),
        ),
    ]
